# Generated by Django 4.0.4 on 2022-05-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyReport', '0002_dailyreport_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='user',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
