# Generated by Django 4.0.4 on 2022-05-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyReport', '0003_alter_dailyreport_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='user',
            field=models.EmailField(max_length=254),
        ),
    ]
