# Generated by Django 4.0.4 on 2022-05-29 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='img',
            new_name='image',
        ),
    ]
