# Generated by Django 4.0.4 on 2022-06-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
                ('author', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
