# Generated by Django 4.0.4 on 2022-06-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('successStory', '0003_alter_successstory_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successstory',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
