# Generated by Django 4.0.4 on 2022-05-18 07:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Policy',
            field=ckeditor.fields.RichTextField(default='testing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
    ]
