# Generated by Django 4.0.4 on 2022-05-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_policy_alter_blog_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Policy',
        ),
    ]
