# Generated by Django 4.0.4 on 2022-05-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightLoss', models.CharField(max_length=200)),
                ('weightGain', models.CharField(max_length=200)),
            ],
        ),
    ]
