# Generated by Django 4.0.4 on 2022-05-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietPrediction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietprediction',
            name='weightGain',
        ),
        migrations.RemoveField(
            model_name='dietprediction',
            name='weightLoss',
        ),
        migrations.AddField(
            model_name='dietprediction',
            name='breakfast',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
        migrations.AddField(
            model_name='dietprediction',
            name='dinner',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
        migrations.AddField(
            model_name='dietprediction',
            name='lunch',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
    ]
