# Generated by Django 4.0.4 on 2022-05-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietPrediction', '0002_remove_dietprediction_weightgain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietprediction',
            name='breakfast',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dietprediction',
            name='dinner',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dietprediction',
            name='lunch',
            field=models.CharField(max_length=200),
        ),
    ]
