# Generated by Django 4.0.4 on 2022-05-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietPrediction', '0003_alter_dietprediction_breakfast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietprediction',
            name='breakfast',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dietprediction',
            name='dinner',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dietprediction',
            name='lunch',
            field=models.FloatField(),
        ),
    ]
