# Generated by Django 4.0.4 on 2022-05-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=254)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=50)),
                ('Weight', models.FloatField()),
                ('Height', models.FloatField()),
                ('Lifestyle', models.CharField(max_length=50)),
                ('Goal', models.CharField(max_length=50)),
                ('BMI', models.FloatField(default=0.0)),
                ('BMR', models.FloatField(default=0.0)),
                ('Calorie_Count', models.FloatField(default=0.0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
