# Generated by Django 4.0.4 on 2022-05-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='user',
            field=models.EmailField(default='anonymous@fitease.com', max_length=250),
        ),
    ]
