# Generated by Django 3.2.11 on 2022-03-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='bmi',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='bmr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='calorie_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='gender',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='goal',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='life_style',
            field=models.CharField(default='Null', max_length=50),
        ),
    ]
