# Generated by Django 3.2.11 on 2022-03-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20220323_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='bmi',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='bmr',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='calorie_count',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='goal',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='life_style',
            field=models.CharField(max_length=50),
        ),
    ]
