# Generated by Django 4.0.4 on 2022-05-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_alter_questionnaire_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='user',
            field=models.EmailField(max_length=250, unique=True),
        ),
    ]
