# Generated by Django 3.2.11 on 2022-03-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_questionnaire_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='bmi',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='bmr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='calorie_count',
            field=models.FloatField(default=0.0),
        ),
    ]
