# Generated by Django 3.2.11 on 2022-03-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20220323_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='life_style',
            new_name='lifestyle',
        ),
    ]
