# Generated by Django 3.2.11 on 2022-03-23 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_rename_life_style_questionnaire_lifestyle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='bmi',
            new_name='BMI',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='bmr',
            new_name='BMR',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='calorie_count',
            new_name='Calorie_Count',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='goal',
            new_name='Goal',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='height',
            new_name='Height',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='lifestyle',
            new_name='Lifestyle',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='weight',
            new_name='Weight',
        ),
    ]
