# Generated by Django 4.0.4 on 2022-05-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_auto_20220324_0124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Name',
            new_name='User',
        ),
    ]
