# Generated by Django 4.0.4 on 2022-05-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisePrediction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseprediction',
            name='exercisePrediction',
            field=models.CharField(max_length=200),
        ),
    ]
