# Generated by Django 4.0.4 on 2022-05-03 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercisePrediction', '0003_exerciseprediction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseprediction',
            name='User',
        ),
    ]
