# Generated by Django 4.0.4 on 2022-05-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisePrediction', '0004_remove_exerciseprediction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseprediction',
            name='exercisePrediction',
        ),
        migrations.AddField(
            model_name='exerciseprediction',
            name='crunches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exerciseprediction',
            name='jogging',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exerciseprediction',
            name='pullups',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exerciseprediction',
            name='pushups',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exerciseprediction',
            name='situps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exerciseprediction',
            name='walking',
            field=models.IntegerField(default=0),
        ),
    ]
