# Generated by Django 4.0.4 on 2022-06-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('user', models.EmailField(max_length=254)),
                ('msg', models.CharField(max_length=200)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
