# Generated by Django 4.0.4 on 2022-06-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyReport',
        ),
    ]
